#端口号
server:
  port: 8087
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: utf-8

#引入配置的log4j2日志文件
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug   #debug时显示sql
        type:
          descriptor:
            sql:
              BasicBinder: trace  #trace时，显示参数

